<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions targetNamespace="urn:samples-switchyard:bpel:1.0" xmlns:tns="urn:samples-switchyard:bpel:1.0"
  xmlns:ws="http://ws.switchyard.samples.redhat.com/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
  xmlns="http://schemas.xmlsoap.org/wsdl/">

  <import namespace="http://ws.switchyard.samples.redhat.com/" location="greeting.wsdl" />

  <plnk:partnerLinkType name="GreetingProcessPLT">
    <plnk:role name="GreetingProcessProvider" portType="ws:GreetingService" />
  </plnk:partnerLinkType>

</definitions>
